# VMs welche erstellt werden sollen. 
vm:
  count: 3
  
  # VM Default Werte - koennen ueberschrieben werden
  cpu: 2
  memory: 2Gi
  storage: 8Gi
  userdata: https://raw.githubusercontent.com/tbz-it/M100/refs/heads/master/cloud-init.yaml 

# Default-Werte koennen pro vm-[0-99] ueberschrieben werden
#vm-0:
#  memory: 1Gi
#  storage: 4Gi
#  userdata: https://raw.githubusercontent.com/tbz-it/M122/refs/heads/master/cloud-init.yaml

# WireGuard Clients. WireGuard erreichbar via Host
wgClients:
  startHostId: 100
  count: 5
  endpointNode: 192.168.1.56
  
# Lokaler Image Cache vorhanden? 
mirror:
  enabled: true
  storage:
    size: 50Gi  
  mirrorBaseUrl: http://192.168.1.56
    
# Bestimmung OS, Version und CPU Architektur  
os:
  family: linux        # linux | windows
  name: ubuntu         # ubuntu | alpine | windows
  variant: noble       # linux: noble, jammy | windows: win10, win11, ws2022
  architecture: arm64  # amd64 | arm64    

images:
  linux:
    ubuntu:
      noble:
        amd64: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
        arm64: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-arm64.img

    alpine:
      edge:
        amd64: https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/generic_alpine-3.23.0-x86_64-bios-cloudinit-r0.qcow2
        arm64: https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/generic_alpine-3.23.2-aarch64-uefi-cloudinit-r0.qcow2

  windows:
    windows:
      win10:
        amd64: https://image-mirror/windows-10-amd64.qcow2
      win11:
        amd64: https://image-mirror/windows-11-amd64.qcow2
      ws2022:
        amd64: https://image-mirror/windows-server-2022-amd64.qcow2
    

  