
# GNS3 
vm:
  count: 1
  
  # VM Default Werte - koennen ueberschrieben werden
  cpu: 2
  memory: 12Gi
  storage: 64Gi
  # braucht einfach ein Eintrag
  userdata: https://raw.githubusercontent.com/tbz-it/M100/refs/heads/master/cloud-init.yaml 
  image:
    name: base-image
    url: http://image-mirror/WindowsServer2022.qcow2

# WireGuard Clients. WireGuard erreichbar via Host
wgClients:
  startHostId: 100
  count: 5
  endpointNode: kv-control
  
# Lokaler Image Cache vorhanden? - http://image-mirror/
mirror:
  enabled: true
  storage:
    size: 50Gi  

os:
  windows: true   