
# GNS3 
vm:
  count: 1
  
  # VM Default Werte - koennen ueberschrieben werden
  cpu: 2
  memory: 12Gi
  storage: 64Gi

os:
  family: windows       # linux | windows
  name: windows         # ubuntu | alpine | windows
  variant: ws2022       # linux: noble, jammy | windows: win10, win11, ws2022
  architecture: amd64   # amd64 | arm64 