#
# Erstellt eine Control Plane Node und zwei Worker Nodes
#

vm:
  count: 3
  
  # Worker Nodes
  cpu: 4
  memory: 8Gi
  storage: 32Gi
  userdata: https://raw.githubusercontent.com/mc-b/lernvirt/refs/heads/main/examples/duk/cloud-init-worker.yaml
  image:
    name: base-image
    url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

# Master
vm-0:
  cpu: 4
  memory: 12Gi
  userdata: https://raw.githubusercontent.com/mc-b/lernvirt/refs/heads/main/examples/duk/cloud-init-control.yaml

wgClients:
  startHostId: 100
  count: 25
  endpointNode: 10.1.40.35

os:
  windows: false     