#
# Erstellt eine Control Plane Node und zwei Worker Nodes
#

vm:
  count: 3
  
  # Worker Nodes
  cpu: 4
  memory: 4Gi
  storage: 32Gi
  userdata: https://raw.githubusercontent.com/mc-b/lernvirt/refs/heads/main/examples/duk/cloud-init-worker.yaml

# Master
vm-0:
  cpu: 4
  memory: 8Gi
  userdata: https://raw.githubusercontent.com/mc-b/lernvirt/refs/heads/main/examples/duk/cloud-init-control.yaml
   