
# VMs welche erstellt werden sollen. 
vm:
  count: 3
  
  # VM Default Werte - koennen ueberschrieben werden
  cpu: 1
  memory: 512Mi
  storage: 1Gi
  userdata: https://raw.githubusercontent.com/mc-b/lernvirt/refs/heads/main/examples/alpine/cloud-init.yaml

os:
  name: alpine         # ubuntu | alpine | windows
  variant: edge       # linux: noble, jammy | windows: win10, win11, ws2022
