
# GNS3 
vm:
  count: 3
  
  # VM Default Werte - koennen ueberschrieben werden
  cpu: 2
  memory: 8Gi
  storage: 48Gi
  userdata: https://raw.githubusercontent.com/mc-b/lerngns3/refs/heads/main/cloud-init-gns3.yaml 
