{{- if .Values.mirror.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-mirror
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-mirror
  template:
    metadata:
      labels:
        app: image-mirror
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: images
              mountPath: /usr/share/nginx/html
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: image-mirror-claim

{{- end }}
